0000;desc="[x46]  SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE 	n.nspname = 'public' AND 	c.relkind = 'r' AND 	c.relname NOT LIKE '_Result%' AND 	c.relname NOT LIKE '_TempResult%';";dur=1787.14
0001;desc="[x48]  SELECT \"View\" FROM \"ViewQuery\"";dur=1578.71
0002;desc="[x37]  SELECT clock_timestamp() \"CurrentDate\"";dur=1172.18
0003;desc="[x10]  SELECT \"PortID\", \"Name\", \"Type\", \"Order\", \"IsKey\", \"SourceColumn\" FROM \"ComposerPortColumn\" ORDER BY \"PortID\" ASC, \"Order\" ASC";dur=1123.67
0004;desc="[x27]  SELECT \"Key\", \"Value\", \"xmin\" FROM ( SELECT \"Key\", \"Value\", \"xmin\" FROM \"ConfigWeb\" UNION ALL  SELECT \"Key\", \"Value\", \"xmin\" FROM \"Config\" WHERE ((\"Config\".\"Key\"<>'FailedWebLogOnAttempts') AND (\"Config\".\"Key\"<>'WebEnabled') AND (\"Config\".\"Key\"<>'WebHelpEmail') AND (\"Config\".\"Key\"<>'WebPasswordResetEnabled') AND (\"Config\".\"Key\"<>'MessageCentreEnabled') AND (\"Config\".\"Key\"<>'DisplayPayeeIDInMessageCentre') AND (\"Config\".\"Key\"<>'NotificationsEnabled') AND (\"Config\".\"Key\"<>'ProfileDropdownEnabled') AND (\"Config\".\"Key\"<>'BrowseProductDocEnabled') AND (\"Config\".\"Key\"<>'EnableHelpType') AND (\"Config\".\"Key\"<>'EnableHelpTypeLink'))) \"fullConfig\" WHERE (((UPPER(CAST(\"fullConfig\".\"Key\" AS varchar))=UPPER('PTZEnabled')) OR (UPPER(CAST(\"fullConfig\".\"Key\" AS varchar))=UPPER('PTZId')) OR (UPPER(CAST(\"fullConfig\".\"Key\" AS varchar))=UPPER('PTZUseInSalesPortal')))) ORDER BY \"Key\" ASC";dur=897.85
0005;desc="[x25]  SELECT \"PresenterFlexValue_\".\"ReportID\", \"PresenterFlexValue_\".\"ValueId\", \"PresenterFlexValue_\".\"SourceID\", \"PresenterFlexValue_\".\"Name\", \"PresenterFlexValue_\".\"ValueType\", \"PresenterFlexValue_\".\"DataType\", \"PresenterFlexValue_\".\"ValueConfig\", \"PresenterFlexValue_\".\"GlobalParamId\" FROM \"PresenterFlexValue_\" WHERE ((\"PresenterFlexValue_\".\"ReportID\"=44))";dur=810.99
0006;desc="[x21]  SELECT \"Reference\".\"ReferenceID\", \"Reference\".\"TableName\", \"Reference\".\"ReferencedTable\", \"ReferenceColumn\".\"ColumnName\", \"ReferenceColumn\".\"ReferencedColumn\", \"Reference\".\"DeleteAction\" FROM \"Reference\" CROSS JOIN \"ReferenceColumn\" WHERE ((\"Reference\".\"ReferenceID\"=\"ReferenceColumn\".\"ReferenceID\") AND (\"Reference\".\"TableName\"='plLabel')) ORDER BY \"Reference\".\"ReferenceID\" ASC, \"ReferenceColumn\".\"Order\" ASC";dur=797.33
0007;desc="[x21]  						SELECT 							nspname as \"BaseSchemaName\", 							relname as \"BaseTableName\", 							attname as \"ColumnName\", 							attname as \"BaseColumnName\", 						    not(attnotnull) as \"AllowDBNull\", 							typname as \"DataTypeName\", 							information_schema._pg_char_max_length(t.oid, atttypmod) as \"ColumnSize\", 							EXISTS( 								SELECT 								FROM pg_index i 								WHERE i.indrelid = a.attrelid AND a.attnum = ANY(i.indkey) AND i.indisprimary 							) as \"IsKey\" 							, ct.\"EffectiveDated\" as \"EffectiveDated\" 						FROM pg_class c 						JOIN pg_namespace n ON n.oid = c.relnamespace 						JOIN pg_attribute a ON a.attrelid = c.oid 						JOIN pg_type t ON t.oid = a.atttypid 						LEFT JOIN \"CustomTable\" ct ON ((ct.\"TableName\" = c.relname) OR ((c.relname LIKE '%_CALCULATED_VIEW_') AND (ct.\"TableName\" = REPLACE(c.relname, '_CALCULATED_VIEW_', '')))) 						WHERE 						    a.attname not in ('tableoid', 'cmax', 'xmax', 'cmin', 'xmin', 'ctid') AND 						    n.nspname = 'public' AND 						    c.relname IN ('plLabel') 						ORDER BY a.attnum; 					";dur=737.05
0008;desc="[x19]  SELECT \"PresenterFlexReport_\".\"ReportID\", \"PresenterFlexReport_\".\"Name\", \"PresenterFlexReport_\".\"WorkflowObjectID\", \"PresenterFlexReport_\".\"ReportMetadata\", \"PresenterFlexReport_\".\"xmin\", \"PresenterFlexReport_\".\"Type\", \"PresenterFlexReport_\".\"RDMID\", \"PresenterFlexReport_\".\"TemplateID\", \"PresenterFlexReport_\".\"IsDraft\" FROM \"PresenterFlexReport_\" WHERE ((\"PresenterFlexReport_\".\"ReportID\"=44))";dur=630.77
0009;desc="[x18]  SELECT \"CustomColumn\".\"TableName\", \"CustomColumn\".\"ColumnName\", \"CustomColumn\".\"Type\", \"CustomColumn\".\"IsKey\", \"ReferenceSource\".\"ReferencedTable\", \"CustomPickList\".\"Name\", \"CustomPickListFilter\".\"Query\" FROM \"CustomColumn\" LEFT JOIN ( SELECT \"Reference\".\"TableName\", \"Reference\".\"ReferencedTable\", \"ReferenceColumn\".\"ColumnName\" FROM \"Reference\" CROSS JOIN \"ReferenceColumn\" WHERE ((\"Reference\".\"ReferenceID\"=\"ReferenceColumn\".\"ReferenceID\"))) \"ReferenceSource\" ON ((\"CustomColumn\".\"TableName\"=\"ReferenceSource\".\"TableName\") AND (\"CustomColumn\".\"ColumnName\"=\"ReferenceSource\".\"ColumnName\")) LEFT JOIN \"CustomPickList\" ON ((\"CustomColumn\".\"TableName\"=\"CustomPickList\".\"TableName\") AND (\"CustomColumn\".\"ColumnName\"=\"CustomPickList\".\"ColumnName\")) LEFT JOIN \"CustomPickListFilter\" ON ((\"CustomPickList\".\"FilterID\"=\"CustomPickListFilter\".\"ID\")) WHERE ((\"CustomColumn\".\"TableName\"='plLabel')) ORDER BY \"CustomColumn\".\"Order\" ASC";dur=592.19
0010;desc="[x18]  SELECT \"ExtendedTableColumn_\".\"Id\", \"ExtendedTableColumn_\".\"TableName\", \"ExtendedTableColumn_\".\"ColumnName\", \"ExtendedTableColumn_\".\"ColumnType\", \"ExtendedTableColumn_\".\"DataType\", \"ExtendedTableColumn_\".\"Order\", \"CalculatedColumn_\".\"Formula\", \"LookupColumn_\".\"LookupTable\", \"LookupColumn_\".\"LookupColumn\" FROM \"ExtendedTableColumn_\" LEFT JOIN \"LookupColumn_\" ON ((\"ExtendedTableColumn_\".\"Id\"=\"LookupColumn_\".\"Id\")) LEFT JOIN \"CalculatedColumn_\" ON ((\"ExtendedTableColumn_\".\"Id\"=\"CalculatedColumn_\".\"Id\")) WHERE ((\"ExtendedTableColumn_\".\"TableName\"='plLabel')) ORDER BY \"Order\" ASC";dur=584.40
0011;desc="[x16]  SELECT \"CustomColumn\".\"TableName\", \"CustomColumn\".\"ColumnName\", \"CustomColumn\".\"Type\", \"CustomColumn\".\"IsKey\", \"ReferenceSource\".\"ReferencedTable\", \"CustomPickList\".\"Name\", \"CustomPickListFilter\".\"Query\" FROM \"CustomColumn\" LEFT JOIN ( SELECT \"Reference\".\"TableName\", \"Reference\".\"ReferencedTable\", \"ReferenceColumn\".\"ColumnName\" FROM \"Reference\" CROSS JOIN \"ReferenceColumn\" WHERE ((\"Reference\".\"ReferenceID\"=\"ReferenceColumn\".\"ReferenceID\"))) \"ReferenceSource\" ON ((\"CustomColumn\".\"TableName\"=\"ReferenceSource\".\"TableName\") AND (\"CustomColumn\".\"ColumnName\"=\"ReferenceSource\".\"ColumnName\")) LEFT JOIN \"CustomPickList\" ON ((\"CustomColumn\".\"TableName\"=\"CustomPickList\".\"TableName\") AND (\"CustomColumn\".\"ColumnName\"=\"CustomPickList\".\"ColumnName\")) LEFT JOIN \"CustomPickListFilter\" ON ((\"CustomPickList\".\"FilterID\"=\"CustomPickListFilter\".\"ID\")) WHERE ((\"CustomColumn\".\"TableName\"='Payee_')) ORDER BY \"CustomColumn\".\"Order\" ASC";dur=570.76
0012;desc="[x17]  						SELECT 							nspname as \"BaseSchemaName\", 							relname as \"BaseTableName\", 							attname as \"ColumnName\", 							attname as \"BaseColumnName\", 						    not(attnotnull) as \"AllowDBNull\", 							typname as \"DataTypeName\", 							information_schema._pg_char_max_length(t.oid, atttypmod) as \"ColumnSize\", 							EXISTS( 								SELECT 								FROM pg_index i 								WHERE i.indrelid = a.attrelid AND a.attnum = ANY(i.indkey) AND i.indisprimary 							) as \"IsKey\" 							, ct.\"EffectiveDated\" as \"EffectiveDated\" 						FROM pg_class c 						JOIN pg_namespace n ON n.oid = c.relnamespace 						JOIN pg_attribute a ON a.attrelid = c.oid 						JOIN pg_type t ON t.oid = a.atttypid 						LEFT JOIN \"CustomTable\" ct ON ((ct.\"TableName\" = c.relname) OR ((c.relname LIKE '%_CALCULATED_VIEW_') AND (ct.\"TableName\" = REPLACE(c.relname, '_CALCULATED_VIEW_', '')))) 						WHERE 						    a.attname not in ('tableoid', 'cmax', 'xmax', 'cmin', 'xmin', 'ctid') AND 						    n.nspname = 'public' AND 						    c.relname IN ('Payee_') 						ORDER BY a.attnum; 					";dur=569.96
0013;desc="[x18]  SELECT *, \"CustomTable\".xmin FROM \"CustomTable\" LEFT JOIN \"_HierarchyCustomTable\" ON ((\"CustomTable\".\"TableName\"=\"_HierarchyCustomTable\".\"TableName\")) WHERE ((\"CustomTable\".\"TableName\"='plLabel')) ORDER BY \"CustomTable\".\"TableName\" ASC";dur=562.90
0014;desc="[x17]  SELECT \"Reference\".\"ReferenceID\", \"Reference\".\"TableName\", \"Reference\".\"ReferencedTable\", \"ReferenceColumn\".\"ColumnName\", \"ReferenceColumn\".\"ReferencedColumn\", \"Reference\".\"DeleteAction\" FROM \"Reference\" CROSS JOIN \"ReferenceColumn\" WHERE ((\"Reference\".\"ReferenceID\"=\"ReferenceColumn\".\"ReferenceID\") AND (\"Reference\".\"TableName\"='Payee_')) ORDER BY \"Reference\".\"ReferenceID\" ASC, \"ReferenceColumn\".\"Order\" ASC";dur=555.57
0015;desc="[x16]  SELECT \"ExtendedTableColumn_\".\"Id\", \"ExtendedTableColumn_\".\"TableName\", \"ExtendedTableColumn_\".\"ColumnName\", \"ExtendedTableColumn_\".\"ColumnType\", \"ExtendedTableColumn_\".\"DataType\", \"ExtendedTableColumn_\".\"Order\", \"CalculatedColumn_\".\"Formula\", \"LookupColumn_\".\"LookupTable\", \"LookupColumn_\".\"LookupColumn\" FROM \"ExtendedTableColumn_\" LEFT JOIN \"LookupColumn_\" ON ((\"ExtendedTableColumn_\".\"Id\"=\"LookupColumn_\".\"Id\")) LEFT JOIN \"CalculatedColumn_\" ON ((\"ExtendedTableColumn_\".\"Id\"=\"CalculatedColumn_\".\"Id\")) WHERE ((\"ExtendedTableColumn_\".\"TableName\"='Payee_')) ORDER BY \"Order\" ASC";dur=537.52
0016;desc="[x16]  SELECT \"Query\" FROM \"CustomPickList\" LEFT JOIN \"CustomPickListFilter\" ON ((\"CustomPickList\".\"FilterID\"=\"CustomPickListFilter\".\"ID\")) WHERE ((\"CustomPickList\".\"TableName\"='Payee_') AND (\"CustomPickList\".\"ColumnName\"='TitleID_'))";dur=532.32
0017;desc="[x16]  SELECT \"Query\" FROM \"CustomPickList\" LEFT JOIN \"CustomPickListFilter\" ON ((\"CustomPickList\".\"FilterID\"=\"CustomPickListFilter\".\"ID\")) WHERE ((\"CustomPickList\".\"TableName\"='Payee_') AND (\"CustomPickList\".\"ColumnName\"='Reports_To_'))";dur=519.93
0018;desc="[x16]  SELECT *, \"CustomTable\".xmin FROM \"CustomTable\" LEFT JOIN \"_HierarchyCustomTable\" ON ((\"CustomTable\".\"TableName\"=\"_HierarchyCustomTable\".\"TableName\")) WHERE ((\"CustomTable\".\"TableName\"='Payee_')) ORDER BY \"CustomTable\".\"TableName\" ASC";dur=511.87
0019;desc="[x16]  SELECT \"Query\" FROM \"CustomPickList\" LEFT JOIN \"CustomPickListFilter\" ON ((\"CustomPickList\".\"FilterID\"=\"CustomPickListFilter\".\"ID\")) WHERE ((\"CustomPickList\".\"TableName\"='Payee_') AND (\"CustomPickList\".\"ColumnName\"='Parent_'))";dur=509.00
0020;desc="[x16]  SELECT \"Query\" FROM \"CustomPickList\" LEFT JOIN \"CustomPickListFilter\" ON ((\"CustomPickList\".\"FilterID\"=\"CustomPickListFilter\".\"ID\")) WHERE ((\"CustomPickList\".\"TableName\"='Payee_') AND (\"CustomPickList\".\"ColumnName\"='Payee_Currency_'))";dur=507.56
0021;desc="[x16]  SELECT \"Query\" FROM \"CustomPickList\" LEFT JOIN \"CustomPickListFilter\" ON ((\"CustomPickList\".\"FilterID\"=\"CustomPickListFilter\".\"ID\")) WHERE ((\"CustomPickList\".\"TableName\"='Payee_') AND (\"CustomPickList\".\"ColumnName\"='Salutation_'))";dur=505.92
0022;desc="[x13]  SELECT DISTINCT \"ExtendedTableColumn_\".\"TableName\" FROM \"ExtendedTableColumn_\"";dur=404.18
0023;desc="[x10]  SELECT \"PortID\", \"PortColumnName\", \"ReferencedTable\", \"ReferencedColumn\" FROM \"PortColumnReference\"";dur=363.53
0024;desc="[x10]  SELECT \"PortID\", \"Name\", \"Type\", \"SourceTable\", \"ReferencedTable\", \"IsWaypoint\", \"xmin\" FROM \"PortDefinition\" ORDER BY \"Name\" ASC";dur=332.03
0025;desc="[x10]  SELECT \"PortID\", \"PortColumnName\", \"ReferencedTimeID\", \"ReferencedLevelID\" FROM \"PortColumnTimeRef\"";dur=320.82
0026;desc="[x10]  SELECT MIN(\"Tagged\".\"ID\") \"ID\" FROM \"Tagged\" GROUP BY \"Tagged\".\"Tag\"";dur=318.44
0027;desc="[x9]  SELECT CAST(COUNT(*) AS integer) \"count\" FROM \"CustomTable\" WHERE ((\"CustomTable\".\"TableName\"='plLabel'))";dur=286.21
0028;desc="[x9] SELECT to_regclass('\"_PFDE_plLabel\"') IS NOT NULL";dur=277.82
0029;desc="[x8]  SELECT CAST(COUNT(*) AS integer) \"count\" FROM \"CustomTable\" WHERE ((\"CustomTable\".\"TableName\"='Payee_'))";dur=271.24
0030;desc="[x8] SELECT to_regclass('\"_PFDE_Payee_\"') IS NOT NULL";dur=256.41
0031;desc="[x7]  SELECT \"DataStoreColumn\".\"ColumnName\", \"DataStoreColumn\".\"ColumnType\", \"DataStoreColumn\".\"IsKey\" FROM \"DataStoreColumn\" WHERE ((\"DataStoreColumn\".\"DataStoreID\"=3)) ORDER BY \"Order\" ASC";dur=244.13
0032;desc="[x7]  SELECT \"DataStoreColumn\".\"ColumnName\", \"DataStoreColumn\".\"ColumnType\", \"DataStoreColumn\".\"IsKey\" FROM \"DataStoreColumn\" WHERE ((\"DataStoreColumn\".\"DataStoreID\"=21)) ORDER BY \"Order\" ASC";dur=227.16
0033;desc="[x7]  SELECT \"DataStoreColumn\".\"ColumnName\", \"DataStoreColumn\".\"ColumnType\", \"DataStoreColumn\".\"IsKey\" FROM \"DataStoreColumn\" WHERE ((\"DataStoreColumn\".\"DataStoreID\"=10)) ORDER BY \"Order\" ASC";dur=222.48
0034;desc="[x2]  SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=44)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=200.01
0035;desc="[x5]  						SELECT 							nspname as \"BaseSchemaName\", 							relname as \"BaseTableName\", 							attname as \"ColumnName\", 							attname as \"BaseColumnName\", 						    not(attnotnull) as \"AllowDBNull\", 							typname as \"DataTypeName\", 							information_schema._pg_char_max_length(t.oid, atttypmod) as \"ColumnSize\", 							EXISTS( 								SELECT 								FROM pg_index i 								WHERE i.indrelid = a.attrelid AND a.attnum = ANY(i.indkey) AND i.indisprimary 							) as \"IsKey\" 							, ct.\"EffectiveDated\" as \"EffectiveDated\" 						FROM pg_class c 						JOIN pg_namespace n ON n.oid = c.relnamespace 						JOIN pg_attribute a ON a.attrelid = c.oid 						JOIN pg_type t ON t.oid = a.atttypid 						LEFT JOIN \"CustomTable\" ct ON ((ct.\"TableName\" = c.relname) OR ((c.relname LIKE '%_CALCULATED_VIEW_') AND (ct.\"TableName\" = REPLACE(c.relname, '_CALCULATED_VIEW_', '')))) 						WHERE 						    a.attname not in ('tableoid', 'cmax', 'xmax', 'cmin', 'xmin', 'ctid') AND 						    n.nspname = 'public' AND 						    c.relname IN ('stgDirectBusinessTransactions_CALCULATED_VIEW_') 						ORDER BY a.attnum; 					";dur=171.14
0036;desc="[x5]  SELECT \"DataStoreColumn\".\"ColumnName\", \"DataStoreColumn\".\"ColumnType\", \"DataStoreColumn\".\"IsKey\" FROM \"DataStoreColumn\" WHERE ((\"DataStoreColumn\".\"DataStoreID\"=17)) ORDER BY \"Order\" ASC";dur=167.42
0037;desc="[x5]  SELECT DISTINCT \"TableName\" FROM \"ExtendedTableColumn_\"";dur=157.12
0038;desc="[x4]  SELECT \"Reference\".\"ReferenceID\", \"Reference\".\"TableName\", \"Reference\".\"ReferencedTable\", \"ReferenceColumn\".\"ColumnName\", \"ReferenceColumn\".\"ReferencedColumn\", \"Reference\".\"DeleteAction\" FROM \"Reference\" CROSS JOIN \"ReferenceColumn\" WHERE ((\"Reference\".\"ReferenceID\"=\"ReferenceColumn\".\"ReferenceID\") AND (\"Reference\".\"TableName\"='cfgRPTTimeParam')) ORDER BY \"Reference\".\"ReferenceID\" ASC, \"ReferenceColumn\".\"Order\" ASC";dur=141.35
0039;desc="[x2]  SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=80)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=138.47
0040;desc="[x4]  SELECT \"ExtendedTableColumn_\".\"Id\", \"ExtendedTableColumn_\".\"TableName\", \"ExtendedTableColumn_\".\"ColumnName\", \"ExtendedTableColumn_\".\"ColumnType\", \"ExtendedTableColumn_\".\"DataType\", \"ExtendedTableColumn_\".\"Order\", \"CalculatedColumn_\".\"Formula\", \"LookupColumn_\".\"LookupTable\", \"LookupColumn_\".\"LookupColumn\" FROM \"ExtendedTableColumn_\" LEFT JOIN \"LookupColumn_\" ON ((\"ExtendedTableColumn_\".\"Id\"=\"LookupColumn_\".\"Id\")) LEFT JOIN \"CalculatedColumn_\" ON ((\"ExtendedTableColumn_\".\"Id\"=\"CalculatedColumn_\".\"Id\")) WHERE ((\"ExtendedTableColumn_\".\"TableName\"='cfgRPTTimeParam')) ORDER BY \"Order\" ASC";dur=136.61
0041;desc="[x4]  SELECT \"DataStoreID\", \"Table\", \"Column\" FROM \"DataStoreTable\" WHERE ((\"DataStoreTable\".\"DataStoreID\"=3))";dur=135.01
0042;desc="[x4]  SELECT \"Name\" FROM \"DataStore\" WHERE ((\"DataStore\".\"DataStoreID\"=10))";dur=134.00
0043;desc="[x4]  SELECT \"Column\", \"Time\", \"Level\" FROM \"DataStoreTimeReference\" WHERE ((\"DataStoreTimeReference\".\"DataStoreID\"=3))";dur=132.41
0044;desc="[x4]  SELECT \"Name\" FROM \"DataStore\" WHERE ((\"DataStore\".\"DataStoreID\"=21))";dur=131.73
0045;desc="[x4]  SELECT \"Column\", \"Target\" FROM \"DataStoreReference\" WHERE ((\"DataStoreReference\".\"DataStoreID\"=3))";dur=129.60
0046;desc="[x4]  SELECT *, \"CustomTable\".xmin FROM \"CustomTable\" LEFT JOIN \"_HierarchyCustomTable\" ON ((\"CustomTable\".\"TableName\"=\"_HierarchyCustomTable\".\"TableName\")) WHERE ((\"CustomTable\".\"TableName\"='cfgRPTTimeParam')) ORDER BY \"CustomTable\".\"TableName\" ASC";dur=128.93
0047;desc="[x4]  SELECT \"DataStoreID\", \"PortID\", \"ColumnName\", \"ColumnType\", \"IsKey\" FROM \"DataStorePort\" WHERE ((\"DataStorePort\".\"DataStoreID\"=3))";dur=128.02
0048;desc="[x4]  						SELECT 							nspname as \"BaseSchemaName\", 							relname as \"BaseTableName\", 							attname as \"ColumnName\", 							attname as \"BaseColumnName\", 						    not(attnotnull) as \"AllowDBNull\", 							typname as \"DataTypeName\", 							information_schema._pg_char_max_length(t.oid, atttypmod) as \"ColumnSize\", 							EXISTS( 								SELECT 								FROM pg_index i 								WHERE i.indrelid = a.attrelid AND a.attnum = ANY(i.indkey) AND i.indisprimary 							) as \"IsKey\" 							, ct.\"EffectiveDated\" as \"EffectiveDated\" 						FROM pg_class c 						JOIN pg_namespace n ON n.oid = c.relnamespace 						JOIN pg_attribute a ON a.attrelid = c.oid 						JOIN pg_type t ON t.oid = a.atttypid 						LEFT JOIN \"CustomTable\" ct ON ((ct.\"TableName\" = c.relname) OR ((c.relname LIKE '%_CALCULATED_VIEW_') AND (ct.\"TableName\" = REPLACE(c.relname, '_CALCULATED_VIEW_', '')))) 						WHERE 						    a.attname not in ('tableoid', 'cmax', 'xmax', 'cmin', 'xmin', 'ctid') AND 						    n.nspname = 'public' AND 						    c.relname IN ('cfgRPTTimeParam') 						ORDER BY a.attnum; 					";dur=125.83
0049;desc="[x4]  SELECT \"DataStoreID\", \"CalculationID\", \"ColumnName\", \"ColumnType\", \"IsKey\" FROM \"DataStoreCalculation\" WHERE ((\"DataStoreCalculation\".\"DataStoreID\"=3))";dur=125.60
0050;desc="[x4]  SELECT \"CustomColumn\".\"TableName\", \"CustomColumn\".\"ColumnName\", \"CustomColumn\".\"Type\", \"CustomColumn\".\"IsKey\", \"ReferenceSource\".\"ReferencedTable\", \"CustomPickList\".\"Name\", \"CustomPickListFilter\".\"Query\" FROM \"CustomColumn\" LEFT JOIN ( SELECT \"Reference\".\"TableName\", \"Reference\".\"ReferencedTable\", \"ReferenceColumn\".\"ColumnName\" FROM \"Reference\" CROSS JOIN \"ReferenceColumn\" WHERE ((\"Reference\".\"ReferenceID\"=\"ReferenceColumn\".\"ReferenceID\"))) \"ReferenceSource\" ON ((\"CustomColumn\".\"TableName\"=\"ReferenceSource\".\"TableName\") AND (\"CustomColumn\".\"ColumnName\"=\"ReferenceSource\".\"ColumnName\")) LEFT JOIN \"CustomPickList\" ON ((\"CustomColumn\".\"TableName\"=\"CustomPickList\".\"TableName\") AND (\"CustomColumn\".\"ColumnName\"=\"CustomPickList\".\"ColumnName\")) LEFT JOIN \"CustomPickListFilter\" ON ((\"CustomPickList\".\"FilterID\"=\"CustomPickListFilter\".\"ID\")) WHERE ((\"CustomColumn\".\"TableName\"='cfgRPTTimeParam')) ORDER BY \"CustomColumn\".\"Order\" ASC";dur=125.43
0051;desc="[x4]  SELECT \"DataStoreID\", \"Name\", \"Definition\", \"xmin\", \"WorkflowObjectID\" FROM \"DataStore\" WHERE ((\"DataStore\".\"DataStoreID\"=3))";dur=124.48
0052;desc=" SELECT \"Reference\".\"ReferenceID\", \"Reference\".\"TableName\", \"Reference\".\"ReferencedTable\", \"ReferenceColumn\".\"ColumnName\", \"ReferenceColumn\".\"ReferencedColumn\", \"Reference\".\"DeleteAction\" FROM \"Reference\" CROSS JOIN \"ReferenceColumn\" WHERE ((\"Reference\".\"ReferenceID\"=\"ReferenceColumn\".\"ReferenceID\")) ORDER BY \"Reference\".\"ReferenceID\" ASC, \"ReferenceColumn\".\"Order\" ASC";dur=118.63
0053;desc="[x2]  SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=46)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=108.89
0054;desc="[x3]  SELECT \"DataStoreID\", \"Table\", \"Column\" FROM \"DataStoreTable\" WHERE ((\"DataStoreTable\".\"DataStoreID\"=10))";dur=106.81
0055;desc="[x3]  SELECT CAST(COUNT(*) AS integer) \"Count\" FROM ( SELECT \"_finalQuery\".\"ID\", \"_finalQuery\".\"TimeID\" FROM ( SELECT \"_RowNumSubQuery\".* FROM ( SELECT *, ROW_NUMBER() OVER( ORDER BY \"ID\" ASC) \"_RowNum\" FROM ( SELECT \"_baseQuery\".\"ID\", \"_baseQuery\".\"TimeID\" FROM ( SELECT * FROM ( SELECT \"plTimePeriod\".\"TimeID\" \"TimeID\", \"plTimePeriod\".\"Description\" \"ID\" FROM ( SELECT \"plTimePeriod\".\"TimeID\", \"plTimePeriod\".\"Description\" FROM \"plTimePeriod\" \"plTimePeriod\") \"plTimePeriod\") \"_DS3\") \"_baseQuery\" WHERE ((\"_baseQuery\".\"TimeID\"='04_PAY CYCLE'))) \"_preRowNumQuery\") \"_RowNumSubQuery\" WHERE ((\"_RowNumSubQuery\".\"_RowNum\">=1) AND (\"_RowNumSubQuery\".\"_RowNum\"<2))) \"_finalQuery\") \"countQuery\"";dur=101.65
0056;desc="[x3]  SELECT \"DataStoreID\", \"CalculationID\", \"ColumnName\", \"ColumnType\", \"IsKey\" FROM \"DataStoreCalculation\" WHERE ((\"DataStoreCalculation\".\"DataStoreID\"=10))";dur=100.93
0057;desc="[x3]  SELECT \"ColumnName\", \"TimeID\", \"LevelID\" FROM \"ReferenceTime\" WHERE ((\"ReferenceTime\".\"TableName\"='plLabel'))";dur=100.35
0058;desc="[x3]  SELECT \"DataStoreID\", \"Table\", \"Column\" FROM \"DataStoreTable\" WHERE ((\"DataStoreTable\".\"DataStoreID\"=21))";dur=97.98
0059;desc="[x3]  SELECT \"DataStoreID\", \"PortID\", \"ColumnName\", \"ColumnType\", \"IsKey\" FROM \"DataStorePort\" WHERE ((\"DataStorePort\".\"DataStoreID\"=21))";dur=97.90
0060;desc=" SELECT \"TableName\", \"ColumnName\", \"ReferencedTable\", \"ReferencedColumn\", \"ReferencedName\" FROM \"CalculationReference\" ORDER BY \"TableName\" ASC";dur=97.71
0061;desc="[x3]  SELECT \"Column\", \"Target\" FROM \"DataStoreReference\" WHERE ((\"DataStoreReference\".\"DataStoreID\"=21))";dur=96.17
0062;desc="[x3]  SELECT \"DataStoreID\", \"Name\", \"Definition\", \"xmin\", \"WorkflowObjectID\" FROM \"DataStore\" WHERE ((\"DataStore\".\"DataStoreID\"=10))";dur=95.69
0063;desc="[x3]  SELECT \"DataStoreID\", \"CalculationID\", \"ColumnName\", \"ColumnType\", \"IsKey\" FROM \"DataStoreCalculation\" WHERE ((\"DataStoreCalculation\".\"DataStoreID\"=21))";dur=94.26
0064;desc="[x3]  SELECT \"Name\" FROM \"DataStore\" WHERE ((\"DataStore\".\"DataStoreID\"=3))";dur=93.39
0065;desc="[x3]  SELECT CAST(COUNT(\"ExtendedTableColumn_\".\"Id\") AS integer) \"count\" FROM \"ExtendedTableColumn_\" WHERE ((\"ExtendedTableColumn_\".\"TableName\"='plLabel'))";dur=93.37
0066;desc=" SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=39)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=93.04
0067;desc="[x3]  SELECT \"Column\", \"Time\", \"Level\" FROM \"DataStoreTimeReference\" WHERE ((\"DataStoreTimeReference\".\"DataStoreID\"=10))";dur=92.77
0068;desc="[x3]  SELECT \"Column\", \"Time\", \"Level\" FROM \"DataStoreTimeReference\" WHERE ((\"DataStoreTimeReference\".\"DataStoreID\"=21))";dur=92.68
0069;desc="[x3]  SELECT \"DataStoreColumn\".\"ColumnName\", \"DataStoreColumn\".\"ColumnType\", \"DataStoreColumn\".\"IsKey\" FROM \"DataStoreColumn\" WHERE ((\"DataStoreColumn\".\"DataStoreID\"=277)) ORDER BY \"Order\" ASC";dur=92.65
0070;desc="[x3]  SELECT \"DataStoreID\", \"PortID\", \"ColumnName\", \"ColumnType\", \"IsKey\" FROM \"DataStorePort\" WHERE ((\"DataStorePort\".\"DataStoreID\"=10))";dur=92.00
0071;desc="[x3]  SELECT \"Column\", \"Target\" FROM \"DataStoreReference\" WHERE ((\"DataStoreReference\".\"DataStoreID\"=10))";dur=91.85
0072;desc="[x3]  SELECT \"DataStoreID\", \"Name\", \"Definition\", \"xmin\", \"WorkflowObjectID\" FROM \"DataStore\" WHERE ((\"DataStore\".\"DataStoreID\"=21))";dur=91.83
0073;desc="[x3]  SELECT \"Name\" FROM \"DataStore\" WHERE ((\"DataStore\".\"DataStoreID\"=17))";dur=90.98
0074;desc="[x2]  SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=42)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=85.47
0075;desc="[x2]  SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=47)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=79.34
0076;desc="[x2]  SELECT \"PresenterFlexReport_\".\"ReportID\", \"PresenterFlexReport_\".\"Name\", \"PresenterFlexReport_\".\"WorkflowObjectID\", \"PresenterFlexReport_\".\"ReportMetadata\", \"PresenterFlexReport_\".\"xmin\", \"PresenterFlexReport_\".\"Type\", \"PresenterFlexReport_\".\"RDMID\", \"PresenterFlexReport_\".\"TemplateID\", \"PresenterFlexReport_\".\"IsDraft\" FROM \"PresenterFlexReport_\" WHERE ((\"PresenterFlexReport_\".\"ReportID\"=42))";dur=76.80
0077;desc=" SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=38)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=76.61
0078;desc="[x2]  SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=36)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=74.85
0079;desc="[x2]  SELECT \"PresenterFlexSourceColumn_\".\"ReportID\", \"PresenterFlexSourceColumn_\".\"SourceID\", \"PresenterFlexSourceColumn_\".\"ColumnName\", \"PresenterFlexSourceColumn_\".\"Editable\", \"PresenterFlexSourceColumn_\".\"BPMFormParameterName\" FROM \"PresenterFlexSourceColumn_\" WHERE ((\"PresenterFlexSourceColumn_\".\"ReportID\"=44) AND (\"PresenterFlexSourceColumn_\".\"SourceID\"=694427864)) ORDER BY \"ReportID\" ASC, \"SourceID\" ASC, \"ColumnName\" ASC";dur=73.30
0080;desc="[x2]  						SELECT 							nspname as \"BaseSchemaName\", 							relname as \"BaseTableName\", 							attname as \"ColumnName\", 							attname as \"BaseColumnName\", 						    not(attnotnull) as \"AllowDBNull\", 							typname as \"DataTypeName\", 							information_schema._pg_char_max_length(t.oid, atttypmod) as \"ColumnSize\", 							EXISTS( 								SELECT 								FROM pg_index i 								WHERE i.indrelid = a.attrelid AND a.attnum = ANY(i.indkey) AND i.indisprimary 							) as \"IsKey\" 							, ct.\"EffectiveDated\" as \"EffectiveDated\" 						FROM pg_class c 						JOIN pg_namespace n ON n.oid = c.relnamespace 						JOIN pg_attribute a ON a.attrelid = c.oid 						JOIN pg_type t ON t.oid = a.atttypid 						LEFT JOIN \"CustomTable\" ct ON ((ct.\"TableName\" = c.relname) OR ((c.relname LIKE '%_CALCULATED_VIEW_') AND (ct.\"TableName\" = REPLACE(c.relname, '_CALCULATED_VIEW_', '')))) 						WHERE 						    a.attname not in ('tableoid', 'cmax', 'xmax', 'cmin', 'xmin', 'ctid') AND 						    n.nspname = 'public' AND 						    c.relname IN ('sysDateStringPeriods') 						ORDER BY a.attnum; 					";dur=72.95
0081;desc="[x2]  SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=45)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=72.35
0082;desc="[x2]  SELECT \"PresenterFlexReport_\".\"ReportID\", \"PresenterFlexReport_\".\"Name\", \"PresenterFlexReport_\".\"WorkflowObjectID\", \"PresenterFlexReport_\".\"ReportMetadata\", \"PresenterFlexReport_\".\"xmin\", \"PresenterFlexReport_\".\"Type\", \"PresenterFlexReport_\".\"RDMID\", \"PresenterFlexReport_\".\"TemplateID\", \"PresenterFlexReport_\".\"IsDraft\" FROM \"PresenterFlexReport_\" WHERE ((\"PresenterFlexReport_\".\"ReportID\"=47))";dur=72.30
0083;desc="[x2]  SELECT DISTINCT \"_finalQuery\".\"ParentID\" FROM ( SELECT \"_RowNumSubQuery\".* FROM ( SELECT *, ROW_NUMBER() OVER( ORDER BY \"ParentID\" ASC) \"_RowNum\" FROM ( SELECT \"_baseQuery\".\"ParentID\" FROM ( SELECT * FROM ( SELECT \"_Result482\".\"Username\" \"UserName\", \"_Result482\".\"ParentDisplayID\" \"ParentID\", \"_Result482\".\"ParentIDName\" \"ParentIDName\", \"_Result482\".\"ParentIDType\" \"ParentIDType\" FROM ( SELECT \"_Result482\".\"Username\", \"_Result482\".\"ParentDisplayID\", \"_Result482\".\"ParentIDName\", \"_Result482\".\"ParentIDType\" FROM ( SELECT \"_Result482\".\"Username\", \"_Result482\".\"ParentDisplayID\", \"_Result482\".\"ParentIDName\", \"_Result482\".\"ParentIDType\" FROM \"_Result482\" UNION ALL  SELECT \"_Result485\".\"Username\" \"Username\", \"_Result485\".\"ParentDisplayID\" \"ParentDisplayID\", \"_Result485\".\"ParentDisplayID\" \"ParentIDName\", \"_Result485\".\"ParentIDType\" \"ParentIDType\" FROM \"_Result485\") \"_Result482\") \"_Result482\") \"_DS21\") \"_baseQuery\" WHERE (((\"_baseQuery\".\"UserName\"='AM.HAMILTON') AND (\"_baseQuery\".\"ParentIDType\"='MASTERID')) AND (\"_baseQuery\".\"ParentID\"IN('ALL')))) \"_preRowNumQuery\") \"_RowNumSubQuery\" WHERE ((\"_RowNumSubQuery\".\"_RowNum\">=1) AND (\"_RowNumSubQuery\".\"_RowNum\"<501))) \"_finalQuery\"";dur=71.62
0084;desc="[x2]  SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=37)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=70.79
0085;desc="[x2]  SELECT CAST(COUNT(*) AS integer) \"Count\" FROM ( SELECT \"_finalQuery\".\"ID\", \"_finalQuery\".\"LabelReportDisplay\" FROM ( SELECT \"_RowNumSubQuery\".* FROM ( SELECT *, ROW_NUMBER() OVER( ORDER BY \"ID\" ASC) \"_RowNum\" FROM ( SELECT \"_baseQuery\".\"ID\", \"_baseQuery\".\"LabelReportDisplay\" FROM ( SELECT * FROM \"plLabel\") \"_baseQuery\" WHERE (((\"_baseQuery\".\"TextLabel\"='ID Type')) AND (\"_baseQuery\".\"ID\"='MASTERID'))) \"_preRowNumQuery\") \"_RowNumSubQuery\" WHERE ((\"_RowNumSubQuery\".\"_RowNum\">=1) AND (\"_RowNumSubQuery\".\"_RowNum\"<2))) \"_finalQuery\") \"countQuery\"";dur=70.18
0086;desc="[x2]  SELECT \"DataStoreID\", \"Table\", \"Column\" FROM \"DataStoreTable\" WHERE ((\"DataStoreTable\".\"DataStoreID\"=17))";dur=69.38
0087;desc="[x2]  SELECT \"ExtendedTableColumn_\".\"Id\", \"ExtendedTableColumn_\".\"TableName\", \"ExtendedTableColumn_\".\"ColumnName\", \"ExtendedTableColumn_\".\"ColumnType\", \"ExtendedTableColumn_\".\"DataType\", \"ExtendedTableColumn_\".\"Order\", \"CalculatedColumn_\".\"Formula\", \"LookupColumn_\".\"LookupTable\", \"LookupColumn_\".\"LookupColumn\" FROM \"ExtendedTableColumn_\" LEFT JOIN \"LookupColumn_\" ON ((\"ExtendedTableColumn_\".\"Id\"=\"LookupColumn_\".\"Id\")) LEFT JOIN \"CalculatedColumn_\" ON ((\"ExtendedTableColumn_\".\"Id\"=\"CalculatedColumn_\".\"Id\")) WHERE ((\"ExtendedTableColumn_\".\"TableName\"='sysTodaysDate')) ORDER BY \"Order\" ASC";dur=69.03
0088;desc=" SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=41)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=68.85
0089;desc=" SELECT \"PresenterFlexComponent_\".\"ReportID\", \"PresenterFlexComponent_\".\"ComponentID\", \"PresenterFlexComponent_\".\"SourceID\", \"PresenterFlexComponent_\".\"ValueID\", \"PresenterFlexComponent_\".\"PaletteId\", \"PresenterFlexComponent_\".\"ComponentType\", \"PresenterFlexComponent_\".\"ComponentConfig\", \"PresenterFlexComponent_\".\"ComponentName\" FROM \"PresenterFlexComponent_\" WHERE ((\"PresenterFlexComponent_\".\"ReportID\"=40)) ORDER BY \"PresenterFlexComponent_\".\"ReportID\" ASC, \"PresenterFlexComponent_\".\"ComponentID\" ASC";dur=68.81
0090;desc="[x2]  SELECT \"_finalQuery\".\"Username\" FROM ( SELECT \"_RowNumSubQuery\".* FROM ( SELECT *, ROW_NUMBER() OVER( ORDER BY \"Username\" ASC) \"_RowNum\" FROM ( SELECT \"_baseQuery\".\"Username\" FROM ( SELECT * FROM \"Payee_\") \"_baseQuery\" WHERE (((\"_baseQuery\".\"PayeeID_\"='128378')))) \"_preRowNumQuery\") \"_RowNumSubQuery\" WHERE ((\"_RowNumSubQuery\".\"_RowNum\">=1) AND (\"_RowNumSubQuery\".\"_RowNum\"<2))) \"_finalQuery\"";dur=68.48
0091;desc="[x2]  SELECT CAST(COUNT(*) AS integer) \"Count\" FROM ( SELECT \"_finalQuery\".\"Name_\", \"_finalQuery\".\"PayeeID_\" FROM ( SELECT \"_RowNumSubQuery\".* FROM ( SELECT *, ROW_NUMBER() OVER( ORDER BY \"Name_\" ASC) \"_RowNum\" FROM ( SELECT \"_baseQuery\".\"Name_\", \"_baseQuery\".\"PayeeID_\" FROM ( SELECT * FROM \"Payee_\") \"_baseQuery\" WHERE ((\"_baseQuery\".\"PayeeID_\"='128378'))) \"_preRowNumQuery\") \"_RowNumSubQuery\" WHERE ((\"_RowNumSubQuery\".\"_RowNum\">=1) AND (\"_RowNumSubQuery\".\"_RowNum\"<2))) \"_finalQuery\") \"countQuery\"";dur=68.08
0092;desc="[x2]  SELECT * FROM ( SELECT DISTINCT * FROM ( SELECT \"_finalQuery\".\"ID\", \"_finalQuery\".\"TimeID\", \"_finalQuery\".\"_RowCount\" FROM ( SELECT \"_baseQuery\".\"ID\", \"_baseQuery\".\"TimeID\", COUNT(*) OVER () \"_RowCount\" FROM ( SELECT * FROM ( SELECT \"plTimePeriod\".\"TimeID\" \"TimeID\", \"plTimePeriod\".\"Description\" \"ID\" FROM ( SELECT \"plTimePeriod\".\"TimeID\", \"plTimePeriod\".\"Description\" FROM \"plTimePeriod\" \"plTimePeriod\") \"plTimePeriod\") \"_DS3\") \"_baseQuery\") \"_finalQuery\") \"externalSelectedQb_\" ORDER BY \"TimeID\" ASC LIMIT 50 ) \"externalSelectedQb_\" UNION ALL  SELECT * FROM ( SELECT DISTINCT * FROM ( SELECT \"_finalQuery\".\"ID\", \"_finalQuery\".\"TimeID\", \"_finalQuery\".\"_RowCount\" FROM ( SELECT \"_baseQuery\".\"ID\", \"_baseQuery\".\"TimeID\", COUNT(*) OVER () \"_RowCount\" FROM ( SELECT * FROM ( SELECT \"plTimePeriod\".\"TimeID\" \"TimeID\", \"plTimePeriod\".\"Description\" \"ID\" FROM ( SELECT \"plTimePeriod\".\"TimeID\", \"plTimePeriod\".\"Description\" FROM \"plTimePeriod\" \"plTimePeriod\") \"plTimePeriod\") \"_DS3\") \"_baseQuery\") \"_finalQuery\") \"externalSelectedQb_\" WHERE ((UPPER(CAST(\"externalSelectedQb_\".\"TimeID\" AS varchar)) = UPPER(CAST('04_PAY CYCLE' AS varchar)) OR (\"externalSelectedQb_\".\"TimeID\" IS NULL AND '04_PAY CYCLE' IS NULL))) ORDER BY \"TimeID\" ASC LIMIT 50 ) \"externalSelectedQb_\"";dur=67.86
0093;desc="[x2]  SELECT CAST(COUNT(*) AS integer) \"count\" FROM \"Users\" WHERE ((\"Users\".\"PayeeID\"='128378'))";dur=67.70
0094;desc="[x2]  						SELECT 							nspname as \"BaseSchemaName\", 							relname as \"BaseTableName\", 							attname as \"ColumnName\", 							attname as \"BaseColumnName\", 						    not(attnotnull) as \"AllowDBNull\", 							typname as \"DataTypeName\", 							information_schema._pg_char_max_length(t.oid, atttypmod) as \"ColumnSize\", 							EXISTS( 								SELECT 								FROM pg_index i 								WHERE i.indrelid = a.attrelid AND a.attnum = ANY(i.indkey) AND i.indisprimary 							) as \"IsKey\" 							, ct.\"EffectiveDated\" as \"EffectiveDated\" 						FROM pg_class c 						JOIN pg_namespace n ON n.oid = c.relnamespace 						JOIN pg_attribute a ON a.attrelid = c.oid 						JOIN pg_type t ON t.oid = a.atttypid 						LEFT JOIN \"CustomTable\" ct ON ((ct.\"TableName\" = c.relname) OR ((c.relname LIKE '%_CALCULATED_VIEW_') AND (ct.\"TableName\" = REPLACE(c.relname, '_CALCULATED_VIEW_', '')))) 						WHERE 						    a.attname not in ('tableoid', 'cmax', 'xmax', 'cmin', 'xmin', 'ctid') AND 						    n.nspname = 'public' AND 						    c.relname IN ('sysTodaysDate') 						ORDER BY a.attnum; 					";dur=67.30
0095;desc="[x2]  SELECT \"_finalQuery\".\"ID\", \"_finalQuery\".\"TimeID\", \"_finalQuery\".\"_RowCount\" FROM ( SELECT \"_baseQuery\".\"ID\", \"_baseQuery\".\"TimeID\", COUNT(*) OVER () \"_RowCount\" FROM ( SELECT * FROM ( SELECT \"plTimePeriod\".\"TimeID\" \"TimeID\", \"plTimePeriod\".\"Description\" \"ID\" FROM ( SELECT \"plTimePeriod\".\"TimeID\", \"plTimePeriod\".\"Description\" FROM \"plTimePeriod\" \"plTimePeriod\") \"plTimePeriod\") \"_DS3\") \"_baseQuery\") \"_finalQuery\" LIMIT 0 ";dur=67.19
0096;desc="[x2]  SELECT \"ExtendedTableColumn_\".\"Id\", \"ExtendedTableColumn_\".\"TableName\", \"ExtendedTableColumn_\".\"ColumnName\", \"ExtendedTableColumn_\".\"ColumnType\", \"ExtendedTableColumn_\".\"DataType\", \"ExtendedTableColumn_\".\"Order\", \"CalculatedColumn_\".\"Formula\", \"LookupColumn_\".\"LookupTable\", \"LookupColumn_\".\"LookupColumn\" FROM \"ExtendedTableColumn_\" LEFT JOIN \"LookupColumn_\" ON ((\"ExtendedTableColumn_\".\"Id\"=\"LookupColumn_\".\"Id\")) LEFT JOIN \"CalculatedColumn_\" ON ((\"ExtendedTableColumn_\".\"Id\"=\"CalculatedColumn_\".\"Id\")) WHERE ((\"ExtendedTableColumn_\".\"TableName\"='sysDateStringPeriods')) ORDER BY \"Order\" ASC";dur=66.83
0097;desc="[x2]  SELECT \"PresenterFlexValue_\".\"ReportID\", \"PresenterFlexValue_\".\"ValueId\", \"PresenterFlexValue_\".\"SourceID\", \"PresenterFlexValue_\".\"Name\", \"PresenterFlexValue_\".\"ValueType\", \"PresenterFlexValue_\".\"DataType\", \"PresenterFlexValue_\".\"ValueConfig\", \"PresenterFlexValue_\".\"GlobalParamId\" FROM \"PresenterFlexValue_\" WHERE ((\"PresenterFlexValue_\".\"ReportID\"=47))";dur=66.79
0098;desc="[x2]  SELECT \"CustomColumn\".\"TableName\", \"CustomColumn\".\"ColumnName\", \"CustomColumn\".\"Type\", \"CustomColumn\".\"IsKey\", \"ReferenceSource\".\"ReferencedTable\", \"CustomPickList\".\"Name\", \"CustomPickListFilter\".\"Query\" FROM \"CustomColumn\" LEFT JOIN ( SELECT \"Reference\".\"TableName\", \"Reference\".\"ReferencedTable\", \"ReferenceColumn\".\"ColumnName\" FROM \"Reference\" CROSS JOIN \"ReferenceColumn\" WHERE ((\"Reference\".\"ReferenceID\"=\"ReferenceColumn\".\"ReferenceID\"))) \"ReferenceSource\" ON ((\"CustomColumn\".\"TableName\"=\"ReferenceSource\".\"TableName\") AND (\"CustomColumn\".\"ColumnName\"=\"ReferenceSource\".\"ColumnName\")) LEFT JOIN \"CustomPickList\" ON ((\"CustomColumn\".\"TableName\"=\"CustomPickList\".\"TableName\") AND (\"CustomColumn\".\"ColumnName\"=\"CustomPickList\".\"ColumnName\")) LEFT JOIN \"CustomPickListFilter\" ON ((\"CustomPickList\".\"FilterID\"=\"CustomPickListFilter\".\"ID\")) WHERE ((\"CustomColumn\".\"TableName\"='sysDateStringPeriods')) ORDER BY \"CustomColumn\".\"Order\" ASC";dur=66.64
0099;desc="[x160] <more items (128 unique)>";dur=5349.34